### ISSUE TITLE
Add ILL link to volume select screen

### ISSUE THREAD

**Issue by mhk33** [cul-it/blacklight-cornell-requests#58]
(Copy of https://issues.library.cornell.edu/browse/DISCOVERYACCESS-2703)

Add something like: 

Don't see your volume? Try Interlibrary Loan.

---

Email thread:

---------- Forwarded message ----------
From: Melissa K. Wallace mhk33@cornell.edu
Date: Wed, May 25, 2016 at 11:57 AM
Subject: Re: Library website feedback from Andy Guerriero ag725@cornell.edu
To: CUL-DA-IMPLEMENTATION-L cul-da-implementation-l@list.cornell.edu

I interpreted this to mean he did a single search for his journal, got to the record in the new catalog, saw the volume he wanted wasn’t in the availability box and didn’t think he should go through the request system because that was only for items Cornell owned. He was experienced and knew we had ILL, so he went to the Library website, but it took too many clicks to get to the ILL page.
https://www.library.cornell.edu/services/request/interlibrary-loan

Though we could follow up with this user to find out if this is what he did and what journal he was looking for.

I guess I wonder if we would want to have a link to the Library's ILL page in the availability area to account for cases where we might not have the volume we need (or just link directly to ILL).

We do have links to ILL and BD, but they are in the collapsed nav in the header. We could also stick them in the footer, but it’s still too far from where the action is.

Maybe this is something we can talk about at the next sprint.

On 5/24/16, 2:30 PM, "bounce-120515387-34666924@list.cornell.edu on behalf of Caitlin M. Finlay" <bounce-120515387-34666924@list.cornell.edu on behalf of cmf7@cornell.edu> wrote:

> I've actually been trying this out this morning. It's not clear if he's using Blacklight or WCL (he says "global library search"), but either way he's correct - there is no link to direct him to ILL after hitting "request" in either catalog.
> 
> When requesting in Blacklight, the patron is  offered the volumes CUL owns, which doesn't help him if we lack a volume. If he selects a volume we own and wants to place a scan request, there is no ILL or scan request link.
> 
> I know the "scan it" button Wendy & I requested would address the article scan issue, but I thought there used to be a link at the bottom for ILL on serials, as "other delivery options." Was that never there?
> 
> Hitting "request" in WCL brings the patron to the Classic option for library delivery only, again no option for ILL.
> 
> Caitlin
> 
> -----Original Message-----
> From: bounce-120515339-73703760@list.cornell.edu [mailto:bounce-120515339-73703760@list.cornell.edu] On Behalf Of Melissa K. Wallace
> Sent: Tuesday, May 24, 2016 2:16 PM
> To: CUL-DA-IMPLEMENTATION-L cul-da-implementation-l@list.cornell.edu
> Subject: FW: Library website feedback from Andy Guerriero ag725@cornell.edu
> 
> On 5/21/16, 9:01 AM, "bounce-120507322-44421873@list.cornell.edu on behalf of Andy Guerriero" <bounce-120507322-44421873@list.cornell.edu on behalf of ag725@cornell.edu> wrote:
> 
> > Enter your comments or questions in the box below: The process of requesting
> > an ILL is unwieldy and complex. I looked up a journal using the global
> > library search and found that the music library holds certain volumes;
> > however, they do not include the one I wanted. There is a button I can mash
> > for Request, but I assumed since it's in the "Availability" box, that's just
> > for copies Cornell has. I happen to know that ILL exists as a service, but if
> > I didn't know that--there is no text anywhere on the page that indicates
> > there is way for me to request an article that Cornell doesn't have. I had to
> > access a different area of your site, Services, to find ILL. It took me
> > several clicks to drill down to where I could actually make a request. The
> > request form is poorly designed and does not reflect modern UX practices for
> > forms. A big problem is that "Title" and "Article Title" should be clearly
> > disambiguated and near each other on the form. I had clicked the link to
> > request an article, and the first field I see on the form is "Title". To me,
> > that logically would be the article title. I had to read the form help text
> > to discover that it was actually requesting the journal title, and then had
> > to scan all the way down the page to find the Article Title field.
> > Additionally, there is a typo in the area of the form where I'm asked if I'm
> > willing to pay for a scan of the article.
> > Browser details: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.11; rv:46.0)
> > Gecko/20100101 Firefox/46.0
> > The most recent page visited: /
> > 
> > Submitted on Saturday, May 21, 2016 - 09:01
> > Submitted by: Andy Guerriero

**Comment by mhk33** [comment]
@Baroquem I added a link to ILL on the main Library website on the volume select screen. However what do you think of linking to ILLiad but autopopulating some of the ILL form? That might be more useful and in line with how we send users to ILL.

**Comment by Baroquem** [comment]
I think this is all complete now, including autopopulation of the form.
