### ISSUE TITLE
Reevaluate handling of bound-withs

### ISSUE THREAD

**Issue by Baroquem** [cul-it/blacklight-cornell-requests#74]
As per this from Erin Eldermire:

"Please see this message from a faculty member, below.  I just went to the record for the item that he notes to try to request it.  When I click request then sign in with my NetID, I get the following page:

[The page you are looking for doesn't exist]

The same message appears in both Firefox and Chrome.

Thank you for any help that you can give on this,
Erin"

------------
This seems to be occurring because the item is flagged as multivol_b, but there's really only one volume, and that one can't actually be requested because it's bound with another item (which is the one that has to be requested).

Item in question: https://newcatalog.library.cornell.edu/catalog/1185113

**Comment by Baroquem** [comment]
JIRA reference: https://issues.library.cornell.edu/browse/DISCOVERYACCESS-2916

**Comment by es287** [comment]
Didn't we talk to Cammie about this -- and she was okay with allowing requests for items like this -- because the staff manually change this into a request for the 'master' item?

**Comment by Baroquem** [comment]
Yes, that's right. I don't think it's an issue with the workflow. I guess the problem is that the request button on that item doesn't work. Something unusual about the particular record?

**Comment by es287** [comment]
do we have the page image? -- maybe there is something about the way the request string is quoted that makes the router not figure out how to handle it.  the error is 'cannot find page' -- it's not that that the request controller failed -- it's that the request never got routed (?).

**Comment by Baroquem** [comment]
Good call, Rick! I just realized what the problem is and how to fix it. I'd been thinking that the use of "Bound with" as an enum value — forming a URL like /request/12345/|Bound with||| — was causing problems. But it's actually that that the code for that rare, one-volume item case, was never updated to use the newer URL format. Should be easy to fix now.

**Comment by Baroquem** [comment]
Fixed
